# Generated by Django 6.0.1 on 2026-01-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_birth_date_person_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hobby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
